# Generated by Django 4.0.3 on 2022-05-11 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=250)),
                ('nacionalidad_cliente', models.CharField(max_length=250)),
                ('tipo_documento_cliente', models.CharField(choices=[('CI', 'CI'), ('Pasaporte', 'Pasaporte'), ('DNI', 'DNI')], max_length=250)),
                ('nro_documento_cliente', models.IntegerField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contacto', models.EmailField(max_length=254)),
                ('tipo_habitacion', models.CharField(choices=[('Standard Suite', 'Standard Suite'), ('Junior Suite', 'Junior Suite'), ('Deluxe Suite', 'Deluxe Suite'), ('Presidential Suite', 'Presidential Suite')], max_length=50)),
                ('comentario', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='contactos',
            fields=[
                ('id_contacto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_contacto', models.CharField(max_length=250)),
                ('nacionalidad_contacto', models.CharField(max_length=250)),
                ('tipo_documento_contacto', models.CharField(max_length=250)),
                ('nro_documento_contacto', models.IntegerField(verbose_name='')),
                ('email_contacto', models.EmailField(max_length=254)),
                ('texto_consulta_contacto', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='habitaciones',
            fields=[
                ('numero_habitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_habitacion', models.CharField(max_length=250)),
                ('camas', models.IntegerField()),
                ('servicios_extras', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente_reserva', models.CharField(max_length=250)),
                ('qde_adultos_reserva', models.IntegerField()),
                ('qde_menores_reserva', models.IntegerField()),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('tipo_habitacion_reserva', models.CharField(choices=[('Standard Suite', 'Standard Suite'), ('Junior Suite', 'Junior Suite'), ('Deluxe Suite', 'Deluxe Suite'), ('Presidential Suite', 'Presidential Suite')], max_length=50)),
                ('email_cliente_reserva', models.EmailField(max_length=254)),
                ('documento', models.ImageField(upload_to='media/documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
