# Generated by Django 3.2 on 2022-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_reserva_tipo_habitacion_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tipo_habitacion_reserva',
            field=models.CharField(max_length=250),
        ),
    ]
