# Generated by Django 3.2 on 2022-04-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_auto_20220413_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='qde_adultos_reserva',
            new_name='cantidad_adultos_reserva',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='qde_menores_reserva',
            new_name='cantidad_menores_reserva',
        ),
    ]
