# Generated by Django 3.2 on 2022-04-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_auto_20220415_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='entrada_reserva',
            new_name='fecha_entrada',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='salida_reserva',
            new_name='fecha_salida',
        ),
    ]
