# Generated by Django 3.2 on 2022-04-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_alter_reserva_id_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='id_reserva',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
