# Generated by Django 4.0.3 on 2022-05-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('comentario', models.CharField(max_length=3000)),
            ],
        ),
    ]
